### ISSUE TITLE
Icon isn't animating appropriately

### ISSUE THREAD

**Issue by lukepighetti** [xvrh/lottie-flutter#57]
https://lottiefiles.com/marketplace/two-tone-weather-icons

Tornado, Thunder Storm, Fog, and Windy do not animate properly.

[lottie-files.zip](https://github.com/xvrh/lottie-flutter/files/4630288/lottie-files.zip)

**Comment by xvrh** [comment]
Hi,
Thanks for the report.

I'll push a fix soon. 
The error was in the "dash" drawing code where we were not using the offset value.

**Comment by lukepighetti** [comment]
Thank you for such a quick response! Is there an ETA for when this will be available on pub?

**Comment by xvrh** [comment]
If you can try my fix with this in your `pubspec.yaml`
```yaml
  lottie:
    git:
      url: https://github.com/xvrh/lottie-flutter.git
      ref: 3c10153c4c08ed1dacc4dec11c6cf606f255b30b
```

If it's ok, I'll deploy the new version today
